In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a[0]

1

In [7]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [8]:
matrix[1,1]

5

In [10]:
matrix[1:,:2]

array([[4, 5],
       [7, 8]])

In [11]:
matrix + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [12]:
matrix2 =  matrix*2
matrix2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [13]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a + 1

array([2, 3, 4])

In [15]:
a < 0

array([False, False, False])

In [17]:
np.count_nonzero(a > 0)

3